services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6000:5432"
    volumes:
      - test_dbdata:/var/lib/postgresql/data

volumes:
  test_dbdata:
